openai:
  base_url: "https://api.openai.com/v1"
  api_key: "your_openai_api_key"
  model: "text-davinci-003"

template_path: "app/prompt_templates/"

channels:
  confluence:
    db_type: "vector"
    db_path: "faiss_index/confluence"
    query_processor: "query_processor_vector"
    data_retrieval: "reretrieval"
    prompt_template: "prompt_template"
    prompt_template_translator: "prompt_template_translator"
    prompt_template_routing: "prompt_template_routing"
    prompt_template_constructor: "prompt_template_constructor"

  serviceNow:
    db_type: "vector"
    db_path: "faiss_index/serviceNow"
    query_processor: "query_processor_sql"
    data_retrieval: "reranking"
    prompt_template: "prompt_template"
    prompt_template_translator: "prompt_sn_translator"
    prompt_template_routing: "prompt_sn_routing"
    prompt_template_constructor: "prompt_sn_constructor"
  # 可以继续添加更多Case
