channels:
  - name: confluence
    data_source: "confluence_api"
    data_processor: "confluence_processor"
    prompt: "prompt_confluence"
    vector_db: "faiss"
    db_config:
      path: "faiss_index"
  - name: sn
    data_source: "service_now_api"
    data_processor: "service_now_processor"
    prompt: "prompt_sn"
    vector_db: "faiss"
    db_config:
      path: "faiss_index"
  # 可以继续添加更多渠道
