openai:
  base_url: "https://api.openai.com/v1"
  api_key: "your_openai_api_key"
  model: "text-davinci-003"

template_path: "app/prompt_templates/"

channels:
  confluence:
    data_loader: "json"
    data_source: "data/confluence"
    data_processor: "json"
    db_type: "vector"
    db_path: "faiss_index/confluence"
    prompt_template_index: "prompt_confluence_index"
    prompt_template_retrieval: "prompt_confluence_retrieval"

  sn:
    data_loader: "json"
    data_source: "data/serviceNow"
    data_processor: "json"
    db_type: "vector"
    db_path: "faiss_index/serviceNow"
    prompt_template_index: "prompt_sn_index"
    prompt_template_retrieval: "prompt_sn_retrieval"
  # 可以继续添加更多Case
