channels:
  - name: confluence
    query_processor: "confluence_processor"
    retrieval_processor: "confluence_processor"
    prompt: "prompt_confluence"
    vector_db: "faiss"
    db_config:
      path: "faiss_index"
  - name: sn
    query_processor: "service_now_processor"
    retrieval_processor: "service_now_processor"
    prompt: "prompt_sn"
    vector_db: "faiss"
    db_config:
      path: "faiss_index"
  # 可以继续添加更多渠道
